package com.dbsl.proposalgenerator.beans;

// Generated Sep 25, 2015 9:10:21 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Details generated by hbm2java
 */
@Entity
@Table(name = "details", catalog = "dbsl_proposal_generator")
public class Details implements java.io.Serializable {

	private Integer id;
	private OtherService otherService;
	private Integer countFrom;
	private Integer countTo;
	private Float rangePrice;
	private Boolean isAcitve;

	public Details() {
	}

	public Details(OtherService otherService) {
		this.otherService = otherService;
	}

	public Details(OtherService otherService, Integer countFrom,
			Integer countTo, Float rangePrice, Boolean isAcitve) {
		this.otherService = otherService;
		this.countFrom = countFrom;
		this.countTo = countTo;
		this.rangePrice = rangePrice;
		this.isAcitve = isAcitve;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OTHER_SERVICE_id", nullable = false)
	public OtherService getOtherService() {
		return this.otherService;
	}

	public void setOtherService(OtherService otherService) {
		this.otherService = otherService;
	}

	@Column(name = "countFrom")
	public Integer getCountFrom() {
		return this.countFrom;
	}

	public void setCountFrom(Integer countFrom) {
		this.countFrom = countFrom;
	}

	@Column(name = "countTo")
	public Integer getCountTo() {
		return this.countTo;
	}

	public void setCountTo(Integer countTo) {
		this.countTo = countTo;
	}

	@Column(name = "rangePrice", precision = 12, scale = 0)
	public Float getRangePrice() {
		return this.rangePrice;
	}

	public void setRangePrice(Float rangePrice) {
		this.rangePrice = rangePrice;
	}

	@Column(name = "isAcitve")
	public Boolean getIsAcitve() {
		return this.isAcitve;
	}

	public void setIsAcitve(Boolean isAcitve) {
		this.isAcitve = isAcitve;
	}

}
